MDEV-24115: Build failure on MacOS on compiling the file btr/btr0btr.cc
Attempt to build MariaDB server on mac OS leads to compilation error:

[ 57%] Building CXX object server-10.5/storage/innobase/CMakeFiles/innobase.dir/btr/btr0btr.cc.o
In file included from server-10.5/storage/innobase/btr/btr0btr.cc:41:
In file included from server-10.5/storage/innobase/include/trx0trx.h:34:
In file included from server-10.5/storage/innobase/include/trx0xa.h:27:
In file included from server-10.5/sql/handler.h:34:
server-10.5/sql/structs.h:877:14: error: implicit conversion loses integer
precision: 'ulong' (aka 'unsigned long') to '__darwin_suseconds_t' (aka 'int')
[-Werror,-Wshorten-64-to-32]
tv_usec= usec;

This error happens in the constructor Timeval(my_time_t sec, ulong usec)

The data member tv_usec of the struct timeval is declared as suseconds_t on MacOS.
Size of suseconds_t is 4 bytes. On the other hand, size of ulong is 8 bytes
on 64-bit MacOS, so attempt to assign a value of wider type (usec) to a value (tv_usec)
of narrower type leads to error.

Declaration of the class Timeval was introduced in 10.4 and since then never changed.
When server 10.4 is built on MacOS the original error message from the bug report
IS NOT generated.

Starting from 10.5 clang compiler starts to emit this error message.

The reason of changes in compiler behaviour is that the extra compiler option
-Wconversion was added to compiler's flags in 10.5.
(see the file storage/innobase/innodb.cmake)

So, to fix the compilation error explicit casting to uint is done before
assignment of an argument value to tv_usec.